---
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped

    ports:
      # These ports must be open
      - '80:80'   # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81'   # Admin Web Port

    environment:
      # PUID: 1000
      # PGID: 1000
      INITIAL_ADMIN_EMAIL: admin@gmail.com
      INITIAL_ADMIN_PASSWORD: Secret123
      DISABLE_IPV6: 'true'

    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
